AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  GoshortenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main
      Runtime: provided.al2023
      Events:
        CreateUrlApi:
          Type: Api
          Properties:
            Path: /
            Method: post
        RedirectUrlApi:
          Type: Api
          Properties:
            Path: /{id}
            Method: get
      Environment:
        Variables:
          DYNAMODB_TABLE: 
            Ref: GoshortenerTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: 
              Ref: GoshortenerTable
    Metadata:
      BuildMethod: go1.x
      
  GoshortenerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH